#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $0 <service_name>"
    exit 1
fi

service_name="$1"

if systemctl is-active --quiet "$service_name"; then
    echo "Service '$service_name' is running."
    exit 0  
else
       echo "Service '$service_name' is not running."
       exit 2  # CRITICAL
fi
